// src/lib/s3Service.test.ts
import { describe, it, expect } from 'vitest';
import * as fc from 'fast-check';

/**
 * Helper function to simulate presigned URL generation
 * This simulates what AWS CLI would return
 */
function generateMockPresignedUrl(
  endpoint: string,
  bucket: string,
  key: string,
  expiresIn: number
): string {
  const baseUrl = `${endpoint}/${bucket}/${key}`;
  const params = new URLSearchParams({
    'X-Amz-Algorithm': 'AWS4-HMAC-SHA256',
    'X-Amz-Credential': 'AKIAIOSFODNN7EXAMPLE/20231201/us-east-1/s3/aws4_request',
    'X-Amz-Date': '20231201T120000Z',
    'X-Amz-Expires': expiresIn.toString(),
    'X-Amz-SignedHeaders': 'host',
    'X-Amz-Signature': 'mock-signature-' + Math.random().toString(36).substring(7),
  });
  return `${baseUrl}?${params.toString()}`;
}

/**
 * Validates that a URL is a properly formatted presigned URL with expiration
 */
function validatePresignedUrl(url: string, expectedExpiresIn?: number): {
  valid: boolean;
  hasExpiration: boolean;
  expirationValue?: number;
  hasRequiredParams: boolean;
} {
  try {
    const parsedUrl = new URL(url);
    
    // Check for required AWS signature parameters
    const hasAlgorithm = parsedUrl.searchParams.has('X-Amz-Algorithm');
    const hasCredential = parsedUrl.searchParams.has('X-Amz-Credential');
    const hasDate = parsedUrl.searchParams.has('X-Amz-Date');
    const hasExpires = parsedUrl.searchParams.has('X-Amz-Expires');
    const hasSignature = parsedUrl.searchParams.has('X-Amz-Signature');
    
    const hasRequiredParams = hasAlgorithm && hasCredential && hasDate && hasExpires && hasSignature;
    
    const expiresParam = parsedUrl.searchParams.get('X-Amz-Expires');
    const expirationValue = expiresParam ? parseInt(expiresParam, 10) : undefined;
    
    const hasExpiration = expiresParam !== null && !isNaN(expirationValue!);
    
    let valid = hasRequiredParams && hasExpiration;
    
    // If expected expiration is provided, verify it matches
    if (expectedExpiresIn !== undefined && expirationValue !== undefined) {
      valid = valid && expirationValue === expectedExpiresIn;
    }
    
    return {
      valid,
      hasExpiration,
      expirationValue,
      hasRequiredParams,
    };
  } catch (error) {
    return {
      valid: false,
      hasExpiration: false,
      hasRequiredParams: false,
    };
  }
}

describe('S3Service - Presigned URL Generation', () => {
  /**
   * Feature: lora-management, Property 12: Presigned URL expiration
   * Validates: Requirements 6.5
   * 
   * For any presigned URL generated for S3 access, the URL should have an expiration time set
   * 
   * This property test verifies that presigned URLs always contain proper expiration parameters.
   * We test the URL format and structure that would be generated by AWS CLI.
   */
  it('Property 12: Presigned URL expiration - all generated URLs should contain expiration parameters', () => {
    fc.assert(
      fc.property(
        // Generate random S3 keys (file paths)
        fc.record({
          key: fc.string({ minLength: 1, maxLength: 100 })
            .filter(s => s.length > 0)
            .map(s => s.replace(/[^a-zA-Z0-9._/-]/g, '_') + '.safetensors'),
          expiresIn: fc.integer({ min: 60, max: 7200 }), // 1 minute to 2 hours
          endpoint: fc.constant('https://test-endpoint.com'),
          bucket: fc.constant('test-bucket'),
        }),
        ({ key, expiresIn, endpoint, bucket }) => {
          // Generate a mock presigned URL (simulating what AWS CLI would return)
          const presignedUrl = generateMockPresignedUrl(endpoint, bucket, key, expiresIn);
          
          // Validate the presigned URL structure
          const validation = validatePresignedUrl(presignedUrl, expiresIn);
          
          // Property assertions:
          // 1. URL must have expiration parameter
          if (!validation.hasExpiration) {
            return false;
          }
          
          // 2. Expiration value must match what was requested
          if (validation.expirationValue !== expiresIn) {
            return false;
          }
          
          // 3. URL must have all required AWS signature parameters
          if (!validation.hasRequiredParams) {
            return false;
          }
          
          // 4. URL must be valid overall
          return validation.valid;
        }
      ),
      { numRuns: 100 }
    );
  });

  describe('Presigned URL validation helper tests', () => {
    it('should validate a properly formatted presigned URL', () => {
      const url = generateMockPresignedUrl(
        'https://test-endpoint.com',
        'test-bucket',
        'test-file.safetensors',
        3600
      );
      
      const validation = validatePresignedUrl(url, 3600);
      
      expect(validation.valid).toBe(true);
      expect(validation.hasExpiration).toBe(true);
      expect(validation.expirationValue).toBe(3600);
      expect(validation.hasRequiredParams).toBe(true);
    });

    it('should reject URLs without expiration parameter', () => {
      const url = 'https://test-endpoint.com/test-bucket/file.safetensors?X-Amz-Algorithm=AWS4-HMAC-SHA256';
      
      const validation = validatePresignedUrl(url);
      
      expect(validation.valid).toBe(false);
      expect(validation.hasExpiration).toBe(false);
    });

    it('should reject URLs with mismatched expiration', () => {
      const url = generateMockPresignedUrl(
        'https://test-endpoint.com',
        'test-bucket',
        'test-file.safetensors',
        3600
      );
      
      const validation = validatePresignedUrl(url, 7200); // Expecting different expiration
      
      expect(validation.valid).toBe(false);
      expect(validation.expirationValue).toBe(3600);
    });

    it('should reject URLs without required AWS parameters', () => {
      const url = 'https://test-endpoint.com/test-bucket/file.safetensors?X-Amz-Expires=3600';
      
      const validation = validatePresignedUrl(url);
      
      expect(validation.valid).toBe(false);
      expect(validation.hasRequiredParams).toBe(false);
    });

    it('should handle invalid URLs gracefully', () => {
      const validation = validatePresignedUrl('not-a-valid-url');
      
      expect(validation.valid).toBe(false);
      expect(validation.hasExpiration).toBe(false);
      expect(validation.hasRequiredParams).toBe(false);
    });
  });

  describe('Mock presigned URL generator tests', () => {
    it('should generate URLs with correct structure', () => {
      const url = generateMockPresignedUrl(
        'https://test-endpoint.com',
        'test-bucket',
        'loras/model.safetensors',
        3600
      );
      
      expect(url).toContain('https://test-endpoint.com/test-bucket/loras/model.safetensors');
      expect(url).toContain('X-Amz-Expires=3600');
      expect(url).toContain('X-Amz-Algorithm=AWS4-HMAC-SHA256');
    });

    it('should generate different signatures for different calls', () => {
      const url1 = generateMockPresignedUrl(
        'https://test-endpoint.com',
        'test-bucket',
        'file1.safetensors',
        3600
      );
      
      const url2 = generateMockPresignedUrl(
        'https://test-endpoint.com',
        'test-bucket',
        'file1.safetensors',
        3600
      );
      
      // URLs should have different signatures (due to random component)
      const sig1 = new URL(url1).searchParams.get('X-Amz-Signature');
      const sig2 = new URL(url2).searchParams.get('X-Amz-Signature');
      
      expect(sig1).not.toBe(sig2);
    });
  });
});
